### ISSUE TITLE
Documentation for Subscriptions?

### ISSUE THREAD

**Issue by mkelzeer** [Enngage/ngx-paypal#143]
Hello, I searched across the repo and found that you added support for Subscriptions. But there is no documentation in the **README** and Pull requests on how it can be used. I tried to figure out with the interfaces but it doesn't seem to work still.
Any help would be appreciated, thanks.

**Comment by Enngage** [comment]
Hi, please look for subscriptions at https://developer.paypal.com/docs/checkout/#try-the-buttons 

It should be the same here as I'm just passing the data along.

**Comment by mkelzeer** [comment]
I believe I'm doing what's in the documentation, and passing the Plan ID for the Subscription as:
```js
createSubscription: (data) => <ICreateSubscriptionRequest> {
   plan_id: 'P-3JS632575S996205SL6BXB4Q'
}
```
But I'm getting **_Error: Expected an subscription id to be passed to createSubscription_** when I click on the button to make a test payment, could you please help with that?

**Comment by Enngage** [comment]
I don't know.. Take a look at developer console in your browser and investigate `Network` tab to see what data is being passed to PayPal. There is not much else I can do.

**Comment by crazyLjuba** [comment]
Just stumbled upon this issue same, but figure out what's the deal.
Instead of this:
```
createSubscription: (data) => <ICreateSubscriptionRequest> {
   plan_id: 'P-3JS632575S996205SL6BXB4Q'
}
```

Try this: 
```
createSubscription: (data, actions) => (
     actions.subscription.create( <ICreateSubscriptionRequest> {
          plan_id: 'PLAN_ID'
     })
)
```

As the createSubscription is expecting the new subscription with a plan_id, so that's the reason of why it's been asking for subscription id.
Checkout here how they did it.
https://developer.paypal.com/docs/subscriptions/integrate/#create-the-subscription

Now after subscription it's sending a new error:
`Use intent=capture to use client-side capture` 
But probably it has something to do with the `onApprove` callback. 
More read...
https://stackoverflow.com/questions/61904177/paypal-subscription-confusion

Hope this solves issue.

**Comment by saranglakare** [comment]
This issue is closed, but the issue itself is unresolved. I found that `createSubscription` option in user given config is simply not supported in the latest version! The code creates it's own `createSubscription` and that is set in the paypal button. The user config's `createSubscription` is thus unused! It is defined `paypal-models.ts` but that's about it.

So as of Jan 2024, the way to create subscription is only on client side using this:

```
      createSubscriptionOnClient: (data) => <ICreateSubscriptionRequest> {
        plan_id: plan_id,
      },
```
where `plan_id` is the ID of a subscription plan you have already created on Paypal (note: this is subscription plan and not a new subscription. A new subscription is per user, but plans are the actual plans that anyone can subscribe to).
