### ISSUE TITLE
'ngx-paypal' is not a known element

### ISSUE THREAD

**Issue by DMZakaria** [Enngage/ngx-paypal#26]
Hi, 
Firstly, thank's for this lib :)

I got a classic error "ngx-paypal' is not a known element",the import in my app-module is good but it does not work when I call ngx-paypal on my template.
My angular version is 5.2.9, I thought it was an issue with the last release (angular 7 update) so I downgrade to 3.2.1, but I got the same error

Any help ?

**Comment by Enngage** [comment]
Hi, this is more of an angular kind of issue because it couldn't find any 'ngx-paypal' component. Could you please take a look at sample Angular demo application to see how its done there? - https://github.com/Enngage/ngx-paypal/tree/master/demo Try to recreate it in your own app. Btw, you should be able to use latest version of this lib in Angular 5 or 6 as well.

**Comment by DMZakaria** [comment]
Hi, thank's for your quick answer.
Issue solved, my module is loaded in lazy mode, I put the import on the child module and it works
Thank's

**Comment by Enngage** [comment]
Awesome, glad to hear that!
