### ISSUE TITLE
TypeError: Cannot read property 'render' of undefined

### ISSUE THREAD

**Issue by botoxparty** [Enngage/ngx-paypal#35]
Hey,

I'm having the exact same issue that's outlined here:

https://github.com/Enngage/ngx-paypal/issues/4

Not sure exactly how it was resolved

**Comment by Enngage** [comment]
Hi, if you cannot read property 'render' it means that the global google's script is not available. Either it was not correctly loaded or it was cleared. I can't say any much more then that without having some information. If this is happening inside tests, you have to make sure to add google's script to karma's config manually so that its available inside tests

**Comment by botoxparty** [comment]
Hey Richard,

The problem occurs exactly as described in that other issue. Works if its
not in a conditional (ngIf) but doesnt when its inside one.

**Comment by botoxparty** [comment]
So to solve this i ended up loading paypal's checkout.js script manually in my component. using something like this...
```
  ngOnInit() {
    this.loadScript();
  }
```

```
  loadScript() {
    let body = <HTMLDivElement> document.body;
            let script = document.createElement('script');
            script.innerHTML = '';
            script.src = 'https://www.paypalobjects.com/api/checkout.js';
            script.async = true;
            script.defer = true;
            body.appendChild(script);
  }
```

**Comment by Enngage** [comment]
Latest version (5.0.x) is a complete refactor and I believe it should solve this issue as well OOTB.
