### ISSUE TITLE
Migrate to new Paypal Javascript SDK (February 2019+)

### ISSUE THREAD

**Issue by Enngage** [Enngage/ngx-paypal#39]
Paypal released new Javascript SDK and this library should switch to it - https://developer.paypal.com/docs/archive/checkout/

**Comment by GuysmoB** [comment]
I started my project some days ago but I got a VALIDATION_ERROR from Paypal. It's because the transaction amount is a dynamic variable, in case it's a hard coded value the transaction works fine. Does this problem is related to the SDK ?

**Comment by wolfen351** [comment]
Paypal doesn't seem to say how long v1 will still be available, so switching should be a priority! :)

**Comment by Enngage** [comment]
Hey, the latest version `5.0.0-beta.1` uses Javascript SDK. Documentation is currently in separate branch - https://github.com/Enngage/ngx-paypal/tree/sdk-migration

**Comment by GetTaxSolutions** [comment]
What is the state of implementation? Is it support PayPalIntegrationType.ServerSideREST?

**Comment by botoxparty** [comment]
`ngx-paypal"' has no exported member 'PayPalEnvironment'`
`ngx-paypal"' has no exported member 'PayPalIntegrationType'`

Went to the node_modules folder and searched within there for these models and couldn't find them. Is there something wrong with the repo?

**Comment by Enngage** [comment]
PayPal's JavaScript sdk no longer needs to distinguish server side & client side integration. I'm pretty much following their integration steps as mentioned here: https://developer.paypal.com/docs/checkout/#how-the-buttons-work 

By default it uses what you could call client side integration, but if you wanted to create payments on server, all you need to so is provide your own implementation of 'onApprove' or 'authorizeOnServer' (in configuration options).

**Comment by GetTaxSolutions** [comment]
Ok, I saw in the documentation that have difference from legacy. I will rewrite my implementation for new SDK.

**Comment by wolfen351** [comment]
Thank you! :)

**Comment by TheWrightDev** [comment]
New sdk seems to be working pretty well, but a couple things I ran into:

Can't seem to do a **prod** build (note that it serves and runs just fine) since importing as `import { NgxPayPalModule } from 'ngx-paypal';` gives:
```
ERROR in : Encountered undefined provider! Usually this means you have a circular dependencies. This might be caused by using 'barrel' index.ts files.
```

and other paths like `import { NgxPayPalModule } from 'ngx-paypal/lib/ngx-paypal.module';` give:
```
ERROR in : Unexpected value 'NgxPayPalModule in C:/proj/node_modules/ngx-paypal/lib/ngx-paypal.module.d.ts' imported by the module 'QuizModule in C:/proj/src/app/modules/test.module.ts'. Please add a @NgModule annotation.
```

Also the `authorizeOnServer` config option expects an observable, but it doesn't actually subscribe and trigger anything with it.

**Comment by Enngage** [comment]
@TheWrightDev thanks a lot for trying that! I've removed the observable from `authorizeOnServer` callback and removed barrel files as they don't really make much sense for the few files I have. 

New version is released under `5.0.0-beta.2`. Let me know if there is anything else I could fix/improve. Thanks again!

**Comment by botoxparty** [comment]
Seems like the readme and docs really need to be updated.

On `5.0.0-beta.2` and i get 

```
ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'config' since it isn't a known property of 'ngx-paypal'.
```

The example in the docs doesn't even import `ICreateOrderRequest`, what the usage for `createOrder()` ?  Obviously theres the PayPal Orders API, is this what it's using? How can you make a transaction without using the Orders API? I just want to charge an amount not create an order with line items.

Thanks

**Comment by GetTaxSolutions** [comment]
I'm also trying 5.0.0-beta.2. And I have this error:

> PaymentComponent.html:203 ERROR TypeError: paypal.Buttons is not a function
>     at NgxPaypalComponent.initPayPal (ngx-paypal.js?1047:319)
>     at NgxPaypalComponent.doPayPalCheck (ngx-paypal.js?1047:207)
>     at NgxPaypalComponent.ngAfterViewInit (ngx-paypal.js?1047:192)
>     at callProviderLifecycles (core.js:22669)

**Comment by botoxparty** [comment]
I also get paypal.Buttons is not a function.

```
ERROR TypeError: paypal.Buttons is not a function
    at NgxPaypalComponent.push../node_modules/ngx-paypal/fesm5/ngx-paypal.js.NgxPaypalComponent.initPayPal (ngx-paypal.js:314)
    at NgxPaypalComponent.push../node_modules/ngx-paypal/fesm5/ngx-paypal.js.NgxPaypalComponent.doPayPalCheck (ngx-paypal.js:202)
    at NgxPaypalComponent.push../node_modules/ngx-paypal/fesm5/ngx-paypal.js.NgxPaypalComponent.ngAfterViewInit (ngx-paypal.js:187)
```

**Comment by botoxparty** [comment]
This is the same problem as V4, if it's within a conditional *ngIf container then `paypal.Buttons` is not a function.

**Comment by GetTaxSolutions** [comment]
I have no *ngIf container and this error is exists.

**Comment by Enngage** [comment]
> Seems like the readme and docs really need to be updated.
> 
> Currently on `5.0.0-beta.2`
> 
> The example in the docs doesn't even import `ICreateOrderRequest`, what the usage for `createOrder()` ? Obviously theres the PayPal Orders API, is this what it's using? How can you make a transaction without using the Orders API? I just want to charge an amount not create an order with line items.
> 
> Thanks

I don't think its possible to do that without Orders API - see this overview https://developer.paypal.com/docs/checkout/#how-the-buttons-work 

The `createOrder` in this library reflects `createOrder` in PayPal's API - https://developer.paypal.com/docs/checkout/integrate/#4-set-up-the-transaction and you cannot make transaction without it. With that said, I don't think you need to specify items if you don't want to. You can just set the amount such as:

```
purchase_units: [{
   amount: {
       value: '0.01'
       }
   }]
```

**Comment by tommmn** [comment]
I am currently use server side payments, so until now , I had both payment and execute server side.
In your new version, I see that you only have authorize the payment in the server, but the createOrder is client side. There is anyway to keep both in the server like the last version?
thanks.

**Comment by GetTaxSolutions** [comment]
I also have this problem. I want to implement this case and return orderId but can't pass it to the component because of ICreateOrderRequest request in definition:
[Server side order set up](https://developer.paypal.com/docs/checkout/reference/server-integration/set-up-transaction/#on-the-server)

**Comment by Enngage** [comment]
This is not very well documented by PayPal, but I think I have an idea how this _might_ work. I'll try taking a look this week.

**Comment by lepidotteri** [comment]
> @Enngage This is not very well documented by PayPal, but I think I have an idea how this might work. I'll try taking a look this week.

This seems documented just fine?
 https://developer.paypal.com/docs/checkout/reference/server-integration/set-up-transaction/#on-the-client

**Comment by tommmn** [comment]
There's nothing wrong with the documentation. The createOrder function returns the orderID, either from client or server. The capture takes an orderID and executes the order. The problem in this implementation is that there's no option to capture the order from server and pass through the orderID, caused by the forced types of the models.

**Comment by lepidotteri** [comment]
@tommmn so does this suffice (where string would be Order.id) ?

`export interface ICreateOrderCallbackActions {
    order: {
        create: (order: string (before: ICreateOrderRequest)) => Promise<any>;
    };
}`

**Comment by tommmn** [comment]
@lepidotteri No, Because he implemented it in a way that only client side could work. If you would check the component code, you would see that createOrder will execute the Object from paypalConfig.createOrder  (ICreateOrderRequest). We should re-implement this part which would check if we want to createOrder via client-side (like what we have now), or to implement it via server-side and return an orderID

**Comment by Enngage** [comment]
yeah, I'll try updating Tomorrow

**Comment by Enngage** [comment]
Can you try `5.0.0-beta.3`? I created two methods - `createOrderOnClient` and `createOrderOnServer` and you need to implement either of these. `createOrderOnServer` expects you to return `Promise<number>` with the PayPal's OrderId. 

Also, I removed the `PayPalConfig` class in favor of simple object with interface:

 ```typescript
const payPalConfig = <IPayPalConfig>{
      currency: 'EUR',
      ...
};
```

**Comment by GetTaxSolutions** [comment]
Can you add also and more details for authorizeOnServer in documentation? It replace onApprove and onClientAuthorization? Right?

**Comment by lepidotteri** [comment]
I don't see `5.0.0-beta.4` on npm, latest version is 9 days ago

**Comment by Enngage** [comment]
Yeah, I added some basic info. If you use `authorizeOnServer`, the `onClientAuthorization` will not be called and transaction will not be verified by the JavaScript SDK. Nothing else changes really.

@lepidotteri it should be there, try now

**Comment by lepidotteri** [comment]
@Enngage I have choosen the 'authorizeOnServer' path, the button displays just fine and 'createOrderOnServer' works fine too; however, the PayPal pop-up window remains always blank because instead of processing the response from my server I get this error on Firefox D.E.: 
`Error: Window cleaned up before response.`

I couldn't test the button on Chrome because of CORB: https://www.chromium.org/Home/chromium-security/corb-for-developers

**Comment by Enngage** [comment]
@lepidotteri Can you try with `5.0.0-beta.5` ? I can't really test it right now, but I changed the signature to return Promise to PayPal so that PayPal can manage it on its own and wait. Maybe it will help.

**Comment by lepidotteri** [comment]
@Enngage just finished migrating my logic to adapt to the new signature and the Error: Window cleaned up before response now appears only seldom. However, there are other problems with createOrderOnServer; this is my code:

```
createOrderOnServer: (data) => this.requestRegistration().then(
                (order: any) => {
                    console.log(data);
                    console.log(order);
                    if (order) {
                        return order.id; // PayPal expects you to return 'orderID' in this method
                    }
                },
```

the console logs empty JSON for both `data `and `order` (order would be the JSON-ified Order class from the Checkout Java SDK (new PayPal sdk for Java)

**Comment by lepidotteri** [comment]
@Enngage also, what can be done about [CORB](https://www.chromium.org/Home/chromium-security/corb-for-developers) on Chromium for example?

**Comment by tommmn** [comment]
@lepidotteri I review the new commit and it seems to work fine. I had no time to test it yet, But I think your problem is that in your createOrderOnServer you should return the result and from the code that you posted its not returned.
* I assume that you return {id: string} from your server

**Comment by lepidotteri** [comment]
@tommmn that's what happens in fact: 
`return order.id; // PayPal expects you to return 'orderID' in this method`

however I return a PayPal Order from the server and not the id as string directly, I extract the id in TypeScript as you can see above

**Comment by tommmn** [comment]
@lepidotteri I just tried the new commit and it works great. You should check your function and make sure that you return the right object.
For me:
```
createOrderOnServer: async data => {
    const _res = await this.paymentService.createOrder(
        this.packageDetails
    );
    return _res.orderID; // Server sends {orderID: string}
},
```

**Comment by lepidotteri** [comment]
@tommmn  @Enngage 

I can too report that everything works as of `5.0.0-beta.5`.

The issues I was experiencing (`Error: Window cleaned up before response.`, `Error: Expected a promise for a string order id to be passed to createOrder`) turned out to be, respectively:

- An issue with *ngIf directives, if you put a spinner, for example, in place of the button while the window was open it will cause that error
- An elusive problem with the new Checkout Java SDK, basically even when forcing PayPal to return newly created Orders as JSON (or `request.prefer("return=representation|minimal"`), the SDK instead always returns only the order id (furthermore, as PLAIN_TEXT). So client-side it was actually only a Http parsing error from Angular HttpClient

**Comment by Seeniea** [comment]
Hello, Enngage.
In my case, following error occured.

core.js:12501 ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'config' since it isn't a known property of 'ngx-payapl'.
1. If 'ngx-payapl' is an Angular component and it has 'config' input, then verify that it is part of this module.
2. If 'ngx-payapl' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    </div>
    <div>
      <ngx-payapl [ERROR ->][config]="payPalConfig"></ngx-payapl>
    </div>
  </div>
"): ng:///CheckoutModule/CheckoutComponent.html@105:18
'ngx-payapl' is not a known element:
1. If 'ngx-payapl' is an Angular component, then verify that it is part of this module.
2. If 'ngx-payapl' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    </div>
    <div>
      [ERROR ->]<ngx-payapl [config]="payPalConfig"></ngx-payapl>
    </div>
  </div>
"): ng:///CheckoutModule/CheckoutComponent.html@105:6
Error: Template parse errors:
Can't bind to 'config' since it isn't a known property of 'ngx-payapl'.
1. If 'ngx-payapl' is an Angular component and it has 'config' input, then verify that it is part of this module.
2. If 'ngx-payapl' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    </div>
    <div>
      <ngx-payapl [ERROR ->][config]="payPalConfig"></ngx-payapl>
    </div>
  </div>
"): ng:///CheckoutModule/CheckoutComponent.html@105:18
'ngx-payapl' is not a known element:
1. If 'ngx-payapl' is an Angular component, then verify that it is part of this module.
2. If 'ngx-payapl' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
    </div>
    <div>
      [ERROR ->]<ngx-payapl [config]="payPalConfig"></ngx-payapl>
    </div>
  </div>
"): ng:///CheckoutModule/CheckoutComponent.html@105:6
    at syntaxError (compiler.js:2547)
    at TemplateParser.push../node_modules/@angular/compiler/fesm5/compiler.js.TemplateParser.parse (compiler.js:19495)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._parseTemplate (compiler.js:25041)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileTemplate (compiler.js:25028)
    at compiler.js:24971
    at Set.forEach (<anonymous>)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileComponents (compiler.js:24971)
    at compiler.js:24881
    at Object.then (compiler.js:2538)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (compiler.js:24880)
    at resolvePromise (zone.js:814)
    at resolvePromise (zone.js:771)
    at zone.js:873
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:14051)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at drainMicroTaskQueue (zone.js:595)

So, I import ngx-paypal into checkout-module, but same same.
Please help me.

**Comment by enzonotario** [comment]
@Seeniea it is `ngx-paypal`, not `ngx-payapl`.

**Comment by Seeniea** [comment]
Wow! Thaks for your quick response.

**Comment by edios-global** [comment]
I am getting two issues in ngx-paypal in mobile app : 

1 .CordovaWebViewImpl: onPageFinished Error   : gets called when i click on pay with debit card or credit card

2 .   Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'nonce-KxtPc+qee490oRFgsXlWt3u4U+MCCndrqxd/rfoDeI31rD2V' 'self' https://*.paypal.com https://*.paypalobjects.com 'unsafe-inline'". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list ;
