### ISSUE TITLE
Difficulties with multiple ngx-paypal components on the same page

### ISSUE THREAD

**Issue by classicPintus** [Enngage/ngx-paypal#57]
Hello,
I'm working with an angular 7 project (Angular CLI version 7.3.7, and Angular version 7.2.11) and Bootstrap 4.

I've two div like that

```
<div class="col-6"><ngx-paypal #paypalMonthly [config]="payPalMonthlyConfig" [registerScript]="false"></ngx-paypal></div>
<div class="col-6"><ngx-paypal #paypalAnnual [config]="payPalAnnualConfig" [registerScript]="false"></ngx-paypal></div>
```

But instead of see them side by side, they are in two different rows. Basically the first one is on the top, and the second one is on the bottom.

The css classes for some reason are ignored or (most likely) I'm missing something?

**Comment by Enngage** [comment]
I really don't think this is related to this component. Are you sure that your columns are sized properly? Did you try it without the components? If it happens with components, what is the size of the paypal buttons? Note that I'm not in control what PayPal renders so if it happens that the size is larger than its wrapper, it might overflow. However, since you say they are stacked, I would bet that your code is not correct.

**Comment by classicPintus** [comment]
Hi @Enngage, I'll try to create a repo with the situation. I hope to find that is my mistake.

I'll back to you very soon, but thank you for your fast answer.

**Comment by classicPintus** [comment]
Hi @Enngage here the repository with the situation
https://github.com/classicPintus/paypal-test

If you hit F5, sometimes the paypal buttons are side by side, and sometims one on top and the other one on the bottom.

Hope it helps

**Comment by Enngage** [comment]
Hi, I'm sorry, but I can't debug this for you. You have to investigate the DOM / styles using browser's DevTools and see why the DOM element is being wrapped. It may be some timing issue caused by the fact that the paypal button width is unknown until rendered. I encountered similar issues like this with angular flex.

**Comment by classicPintus** [comment]
Hi @Enngage,
clear but why the issue is closed?
The problem is still there as far as I know

**Comment by Enngage** [comment]
Because I dont see how its related to this library. The only thing Im
rendering is a div without any styles where I instruct PayPal to render the
button. If there is some style / DOM wrapping problem, its likely caused by
external code.

You have to investigate DOM on your end and see whats going on.

**Comment by classicPintus** [comment]
Ok. More clear now. Thank you

**Comment by Pho3niX90** [comment]
@classicPintus did you ever get to the bottom of this, seeing this exact behaviour now.

**Comment by Pho3niX90** [comment]
@Enngage this is an issue in this lib, the div you are rendering is assigning the very same ids to all components. Please see my PR.

**Comment by classicPintus** [comment]
> 

We have changed the UI and now we have one single component in the page
