### ISSUE TITLE
[feature request] Input() disabled

### ISSUE THREAD

**Issue by spartanPAGE** [Enngage/ngx-paypal#8]
I'd like to be able to disable the paypal button (i.e. when a info checkbox is not checked) without magic

**Comment by Enngage** [comment]
I'm not sure how this should be implemented. I'm not responsible for generating/styling the paypal button - PayPal is. As far as I know, there is not a `disabled` state for PayPal button. If you don't want to show the paypal button, simply hide the component with i.e. `*ngIf` until all your data is valid.

**Comment by jh-code** [comment]
When I use `*ngIf` to hide the component and initialize the PayPalConfig in `ngOnInit` I get an instant `onError` event that triggers a popup that I made to say there was an error with the payment. I think a disabled feature would be great because for my payment, a form is required to be valid before payment can be made, unless there is another way to do it.

**Comment by nodehack** [comment]
> When I use `*ngIf` to hide the component and initialize the PayPalConfig in `ngOnInit` I get an instant `onError` event that triggers a popup that I made to say there was an error with the payment. I think a disabled feature would be great because for my payment, a form is required to be valid before payment can be made, unless there is another way to do it.

You can wrap the `<ngx-paypal>` element in a `<div>` and do your disable/enable logic using css and `[ngClass]`.  

Something like:
```
.disabled {
  opacity: .2;
  pointer-events: none;
  touch-action: none;
}
```

**Comment by Enngage** [comment]
The above is the way to do this, closing for now.
